
//CTOR of product 
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const Product = new Schema({
    //ID is generated by Mongo Automatically
    name: {
        type: String,
        required:true
    },
    image: {
        type: String,
        required:true
    },
    video: {
        type: String,
        required:true
    },
    brand: {
        type: String,
        required:true
    },description: {
        type: String,
        required:true
    },
    category: {
        type: String,
        required:true
    },
    amountInInventory: {
        type: Integer,
        required:true
    },supplier: {
        type: String,
        required:true
    },
});

//exporting it to controler 
module.exports = mongoose.model('productsmodel',Product)